.Dd March 12, 2021
.Dt SFEED_WEB 1
.Os
.Sh NAME
.Nm sfeed_web
.Nd finds URLs to feeds from a HTML webpage
.Sh SYNOPSIS
.Nm
.Op Ar baseurl
.Sh DESCRIPTION
.Nm
reads the HTML website as XML or HTML data from stdin and writes the found
URLs to stdout.
.Sh OPTIONS
.Bl -tag -width 8n
.It Ar baseurl
Optional base URL to use for found feed URLs that are relative.
.El
.Sh OUTPUT FORMAT
url<TAB>content-type<newline>
.Bl -tag -width Ds
.It url
Found relative or absolute URL.
.Pp
For relative URLs if a <base href="..." /> tag is found it will be used,
otherwise if the
.Ar baseurl
option is specified then that is used, if neither are set then the relative URL
is printed.
.It content-type
Usually application/atom+xml or application/rss+xml.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Get URLs from xkcd website:
.Bd -literal
curl -s -L 'http://www.xkcd.com/' | sfeed_web 'http://www.xkcd.com/'
.Ed
.Sh SEE ALSO
.Xr sfeed_update 1 ,
.Xr sh 1
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
